Name:           ros-indigo-ceres-solver
Version:        0.10.0
Release:        2%{?dist}
Summary:        ROS ceres_solver package

Group:          Development/Libraries
License:        New BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       blas-devel
Requires:       gflags-devel
Requires:       glog-devel
Requires:       lapack-devel
Requires:       ros-indigo-catkin
Requires:       suitesparse-devel
Requires:       tbb-devel
BuildRequires:  blas-devel
BuildRequires:  cmake
BuildRequires:  gflags-devel
BuildRequires:  glog-devel
BuildRequires:  lapack-devel
BuildRequires:  suitesparse-devel
BuildRequires:  tbb-devel

%description
Ceres Solver - A non-linear least squares minimizer

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Jan 14 2015 Daniel Stonier <d.stonier@gmail.com> - 0.10.0-2
- Autogenerated by Bloom

* Wed Jan 14 2015 Daniel Stonier <d.stonier@gmail.com> - 0.10.0-0
- Autogenerated by Bloom

* Wed Jan 14 2015 Daniel Stonier <d.stonier@gmail.com> - 0.10.0-1
- Autogenerated by Bloom

